'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 bronze_penny.glb --transform 
Files: bronze_penny.glb [2.56MB] > /Users/jamaldeallie/Downloads/09-shadows-final/bronze_penny-transformed.glb [142.7KB] (94%)
Author: 2crabs (https://sketchfab.com/2crabs)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bronze-penny-71199b86b8874de5a8823453c266e0e8
Title: Bronze penny
*/

import { Float,useGLTF } from '@react-three/drei';
import React from 'react';
import { Mesh } from 'three';

const OldPenny = () => {
  const { nodes, materials } = useGLTF('/models/bronze_penny-transformed.glb');
  const mesh = nodes.Object_2 as Mesh;

  return (
    <Float
      speed={1} // Animation speed, defaults to 1
      rotationIntensity={1} // XYZ rotation intensity, defaults to 1
      floatIntensity={1} // Up/down float intensity, works like a multiplier with floatingRange,defaults to 1
      floatingRange={[-0.075, 0.1]} // Range of y-axis values the object will float within, defaults to [-0.1,0.1]
    >
      <mesh
        geometry={mesh.geometry}
        material={materials['Material.001']}
        rotation={[0, 3.2, 9.45]}
        position={[0, .05, 0.5]}
        scale={0.75}
    
      />
    </Float>
  );
};

useGLTF.preload('models/bronze_penny-transformed.glb');

export default OldPenny;
