import { ReactNode, Suspense } from 'react';

import type { Metadata } from 'next';

import './globals.css';

import { Footer, Lenify } from '@/components';

import { Einer_Grotesk, Sunday_Afternoon } from '@/fonts';

import dynamic from 'next/dynamic';

const SiteHeader = dynamic(
  () => import('@/components').then(mod => mod.SiteHeader),
  { ssr: false }
);

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <body
        className={`${Einer_Grotesk.variable} ${Sunday_Afternoon.variable}`}
        suppressHydrationWarning={true}>
        <Suspense fallback={null}>
          <Lenify />
        </Suspense>
        <SiteHeader />
        <Suspense fallback={null}>{children}</Suspense>
        <Footer />
      </body>
    </html>
  );
}
