import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Wrapper } from '@/components';
import { Einer_Grotesk, Sunday_Afternoon } from '@/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${Einer_Grotesk.variable} ${Sunday_Afternoon.variable}`}
        suppressHydrationWarning={true}>
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
